"""
Canonical 150-stock NSE universe with cap tier classification and sectors.
Includes 50 Large Cap, 50 Mid Cap, and 50 Small Cap stocks.
"""

NSE_UNIVERSE = [
    # === LARGE CAP (50 Stocks) ===
    {"symbol": "RELIANCE", "name": "Reliance Industries Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "TCS", "name": "Tata Consultancy Services Ltd.", "sector": "Technology", "cap": "Large"},
    {"symbol": "HDFCBANK", "name": "HDFC Bank Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "ICICIBANK", "name": "ICICI Bank Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "INFY", "name": "Infosys Ltd.", "sector": "Technology", "cap": "Large"},
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel Ltd.", "sector": "Telecommunication", "cap": "Large"},
    {"symbol": "SBIN", "name": "State Bank of India", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "LICI", "name": "Life Insurance Corporation of India", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "ITC", "name": "ITC Ltd.", "sector": "Consumer Goods", "cap": "Large"},
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd.", "sector": "Consumer Goods", "cap": "Large"},
    {"symbol": "LT", "name": "Larsen & Toubro Ltd.", "sector": "Construction", "cap": "Large"},
    {"symbol": "AXISBANK", "name": "Axis Bank Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "HCLTECH", "name": "HCL Technologies Ltd.", "sector": "Technology", "cap": "Large"},
    {"symbol": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd.", "sector": "Healthcare", "cap": "Large"},
    {"symbol": "NTPC", "name": "NTPC Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "MARUTI", "name": "Maruti Suzuki India Ltd.", "sector": "Automobile", "cap": "Large"},
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement Ltd.", "sector": "Materials", "cap": "Large"},
    {"symbol": "TATASTEEL", "name": "Tata Steel Ltd.", "sector": "Materials", "cap": "Large"},
    {"symbol": "COALINDIA", "name": "Coal India Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "POWERGRID", "name": "Power Grid Corporation of India Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "WIPRO", "name": "Wipro Ltd.", "sector": "Technology", "cap": "Large"},
    {"symbol": "ASIANPAINT", "name": "Asian Paints Ltd.", "sector": "Consumer Goods", "cap": "Large"},
    {"symbol": "M&M", "name": "Mahindra & Mahindra Ltd.", "sector": "Automobile", "cap": "Large"},
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "ADANIENT", "name": "Adani Enterprises Ltd.", "sector": "Metals & Mining", "cap": "Large"},
    {"symbol": "ADANIPORTS", "name": "Adani Ports & SEZ Ltd.", "sector": "Services", "cap": "Large"},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "TITAN", "name": "Titan Company Ltd.", "sector": "Consumer Goods", "cap": "Large"},
    {"symbol": "JSWSTEEL", "name": "JSW Steel Ltd.", "sector": "Materials", "cap": "Large"},
    {"symbol": "ONGC", "name": "Oil & Natural Gas Corporation Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "HAL", "name": "Hindustan Aeronautics Ltd.", "sector": "Capital Goods", "cap": "Large"},
    {"symbol": "TRENT", "name": "Trent Ltd.", "sector": "Consumer Services", "cap": "Large"},
    {"symbol": "ADANIPOWER", "name": "Adani Power Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "GRASIM", "name": "Grasim Industries Ltd.", "sector": "Materials", "cap": "Large"},
    {"symbol": "JIOFIN", "name": "Jio Financial Services Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "BPCL", "name": "Bharat Petroleum Corporation Ltd.", "sector": "Energy", "cap": "Large"},
    {"symbol": "HINDALCO", "name": "Hindalco Industries Ltd.", "sector": "Materials", "cap": "Large"},
    {"symbol": "SBILIFE", "name": "SBI Life Insurance Company Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "TECHM", "name": "Tech Mahindra Ltd.", "sector": "Technology", "cap": "Large"},
    {"symbol": "BEL", "name": "Bharat Electronics Ltd.", "sector": "Capital Goods", "cap": "Large"},
    {"symbol": "DLF", "name": "DLF Ltd.", "sector": "Construction", "cap": "Large"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance Company Ltd.", "sector": "Financial Services", "cap": "Large"},
    {"symbol": "BRITANNIA", "name": "Britannia Industries Ltd.", "sector": "Consumer Goods", "cap": "Large"},
    {"symbol": "CIPLA", "name": "Cipla Ltd.", "sector": "Healthcare", "cap": "Large"},
    {"symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories Ltd.", "sector": "Healthcare", "cap": "Large"},
    {"symbol": "EICHERMOT", "name": "Eicher Motors Ltd.", "sector": "Automobile", "cap": "Large"},

    # === MID CAP (50 Stocks) ===
    {"symbol": "AUBANK", "name": "AU Small Finance Bank Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "BALKRISIND", "name": "Balkrishna Industries Ltd.", "sector": "Automobile", "cap": "Mid"},
    {"symbol": "BANDHANBNK", "name": "Bandhan Bank Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "BATAINDIA", "name": "Bata India Ltd.", "sector": "Consumer Goods", "cap": "Mid"},
    {"symbol": "BHARATFORG", "name": "Bharat Forge Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "BIOCON", "name": "Biocon Ltd.", "sector": "Healthcare", "cap": "Mid"},
    {"symbol": "CONCOR", "name": "Container Corporation of India Ltd.", "sector": "Services", "cap": "Mid"},
    {"symbol": "CUMMINSIND", "name": "Cummins India Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "ESCORTS", "name": "Escorts Kubota Ltd.", "sector": "Automobile", "cap": "Mid"},
    {"symbol": "FEDERALBNK", "name": "The Federal Bank Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "GODREJPROP", "name": "Godrej Properties Ltd.", "sector": "Construction", "cap": "Mid"},
    {"symbol": "GUJGASLTD", "name": "Gujarat Gas Ltd.", "sector": "Energy", "cap": "Mid"},
    {"symbol": "HINDPETRO", "name": "Hindustan Petroleum Corporation Ltd.", "sector": "Energy", "cap": "Mid"},
    {"symbol": "IDFCFIRSTB", "name": "IDFC First Bank Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "IRCTC", "name": "Indian Railway Catering & Tourism Corporation Ltd.", "sector": "Consumer Services", "cap": "Mid"},
    {"symbol": "JINDALSTEL", "name": "Jindal Steel & Power Ltd.", "sector": "Materials", "cap": "Mid"},
    {"symbol": "LICHSGFIN", "name": "LIC Housing Finance Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "MRF", "name": "MRF Ltd.", "sector": "Automobile", "cap": "Mid"},
    {"symbol": "MUTHOOTFIN", "name": "Muthoot Finance Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "NATIONALUM", "name": "National Aluminium Company Ltd.", "sector": "Materials", "cap": "Mid"},
    {"symbol": "OBEROIRLTY", "name": "Oberoi Realty Ltd.", "sector": "Construction", "cap": "Mid"},
    {"symbol": "PAGEIND", "name": "Page Industries Ltd.", "sector": "Consumer Goods", "cap": "Mid"},
    {"symbol": "PFC", "name": "Power Finance Corporation Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "PNB", "name": "Punjab National Bank", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "POLYCAB", "name": "Polycab India Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "RECLTD", "name": "REC Ltd.", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "SAIL", "name": "Steel Authority of India Ltd.", "sector": "Materials", "cap": "Mid"},
    {"symbol": "SRF", "name": "SRF Ltd.", "sector": "Chemicals", "cap": "Mid"},
    {"symbol": "TATACOMM", "name": "Tata Communications Ltd.", "sector": "Telecommunication", "cap": "Mid"},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi Ltd.", "sector": "Technology", "cap": "Mid"},
    {"symbol": "TATAPOWER", "name": "Tata Power Company Ltd.", "sector": "Energy", "cap": "Mid"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power Ltd.", "sector": "Energy", "cap": "Mid"},
    {"symbol": "TVSMOTOR", "name": "TVS Motor Company Ltd.", "sector": "Automobile", "cap": "Mid"},
    {"symbol": "UNIONBANK", "name": "Union Bank of India", "sector": "Financial Services", "cap": "Mid"},
    {"symbol": "VOLTAS", "name": "Voltas Ltd.", "sector": "Consumer Goods", "cap": "Mid"},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland Ltd.", "sector": "Automobile", "cap": "Mid"},
    {"symbol": "ASTRAL", "name": "Astral Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "DEEPAKNTR", "name": "Deepak Nitrite Ltd.", "sector": "Chemicals", "cap": "Mid"},
    {"symbol": "DIXON", "name": "Dixon Technologies (India) Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "IPCALAB", "name": "Ipca Laboratories Ltd.", "sector": "Healthcare", "cap": "Mid"},
    {"symbol": "MAXHEALTH", "name": "Max Healthcare Institute Ltd.", "sector": "Healthcare", "cap": "Mid"},
    {"symbol": "MPHASIS", "name": "Mphasis Ltd.", "sector": "Technology", "cap": "Mid"},
    {"symbol": "PERSISTENT", "name": "Persistent Systems Ltd.", "sector": "Technology", "cap": "Mid"},
    {"symbol": "PIIND", "name": "PI Industries Ltd.", "sector": "Chemicals", "cap": "Mid"},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries Ltd.", "sector": "Capital Goods", "cap": "Mid"},
    {"symbol": "SYNGENE", "name": "Syngene International Ltd.", "sector": "Healthcare", "cap": "Mid"},
    {"symbol": "TATACHEM", "name": "Tata Chemicals Ltd.", "sector": "Chemicals", "cap": "Mid"},

    # === SMALL CAP (50 Stocks) ===
    {"symbol": "AEGISLOG", "name": "Aegis Logistics Ltd.", "sector": "Services", "cap": "Small"},
    {"symbol": "APLLTD", "name": "Alembic Pharmaceuticals Ltd.", "sector": "Healthcare", "cap": "Small"},
    {"symbol": "AVANTIFEED", "name": "Avanti Feeds Ltd.", "sector": "Consumer Goods", "cap": "Small"},
    {"symbol": "BBOX", "name": "Black Box Ltd.", "sector": "Technology", "cap": "Small"},
    {"symbol": "BIRLACORPN", "name": "Birla Corporation Ltd.", "sector": "Materials", "cap": "Small"},
    {"symbol": "BLUESTARCO", "name": "Blue Star Ltd.", "sector": "Consumer Goods", "cap": "Small"},
    {"symbol": "CAMPUS", "name": "Campus Activewear Ltd.", "sector": "Consumer Goods", "cap": "Small"},
    {"symbol": "CASTROLIND", "name": "Castrol India Ltd.", "sector": "Chemicals", "cap": "Small"},
    {"symbol": "CESC", "name": "CESC Ltd.", "sector": "Energy", "cap": "Small"},
    {"symbol": "COCHINSHIP", "name": "Cochin Shipyard Ltd.", "sector": "Capital Goods", "cap": "Small"},
    {"symbol": "CSBBANK", "name": "CSB Bank Ltd.", "sector": "Financial Services", "cap": "Small"},
    {"symbol": "CYIENT", "name": "Cyient Ltd.", "sector": "Technology", "cap": "Small"},
    {"symbol": "EIDPARRY", "name": "E.I.D. - Parry (India) Ltd.", "sector": "Consumer Goods", "cap": "Small"},
    {"symbol": "EIHOTEL", "name": "EIH Ltd.", "sector": "Consumer Services", "cap": "Small"},
    {"symbol": "ENGINERSIN", "name": "Engineers India Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "EQUITASBNK", "name": "Equitas Small Finance Bank Ltd.", "sector": "Financial Services", "cap": "Small"},
    {"symbol": "FSL", "name": "Firstsource Solutions Ltd.", "sector": "Technology", "cap": "Small"},
    {"symbol": "GHCL", "name": "GHCL Ltd.", "sector": "Chemicals", "cap": "Small"},
    {"symbol": "GLENMARK", "name": "Glenmark Pharmaceuticals Ltd.", "sector": "Healthcare", "cap": "Small"},
    {"symbol": "GPPL", "name": "Gujarat Pipavav Port Ltd.", "sector": "Services", "cap": "Small"},
    {"symbol": "GRINFRA", "name": "G R Infraprojects Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "HAPPYFORGE", "name": "Happy Forgings Ltd.", "sector": "Capital Goods", "cap": "Small"},
    {"symbol": "HEG", "name": "HEG Ltd.", "sector": "Materials", "cap": "Small"},
    {"symbol": "HFCL", "name": "HFCL Ltd.", "sector": "Telecommunication", "cap": "Small"},
    {"symbol": "HGINFRA", "name": "H.G. Infra Engineering Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "HUDCO", "name": "Housing & Urban Development Corporation Ltd.", "sector": "Financial Services", "cap": "Small"},
    {"symbol": "IBREALEST", "name": "Indiabulls Real Estate Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "INDIGOPNTS", "name": "Indigo Paints Ltd.", "sector": "Consumer Goods", "cap": "Small"},
    {"symbol": "IONEXCHANG", "name": "Ion Exchange (India) Ltd.", "sector": "Capital Goods", "cap": "Small"},
    {"symbol": "IRCON", "name": "Ircon International Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "ITDC", "name": "India Tourism Development Corporation Ltd.", "sector": "Consumer Services", "cap": "Small"},
    {"symbol": "JKTYRE", "name": "JK Tyre & Industries Ltd.", "sector": "Automobile", "cap": "Small"},
    {"symbol": "JSL", "name": "Jindal Stainless Ltd.", "sector": "Materials", "cap": "Small"},
    {"symbol": "KEC", "name": "KEC International Ltd.", "sector": "Capital Goods", "cap": "Small"},
    {"symbol": "KPITTECH", "name": "KPIT Technologies Ltd.", "sector": "Technology", "cap": "Small"},
    {"symbol": "MAHLIFE", "name": "Mahindra Lifespace Developers Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "METROPOLIS", "name": "Metropolis Healthcare Ltd.", "sector": "Healthcare", "cap": "Small"},
    {"symbol": "MOLDTECH", "name": "Mold-Tek Technologies Ltd.", "sector": "Technology", "cap": "Small"},
    {"symbol": "NBCC", "name": "NBCC (India) Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "NCC", "name": "NCC Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "NLCINDIA", "name": "NLC India Ltd.", "sector": "Energy", "cap": "Small"},
    {"symbol": "PTC", "name": "PTC India Ltd.", "sector": "Financial Services", "cap": "Small"},
    {"symbol": "RAILTEL", "name": "RailTel Corporation of India Ltd.", "sector": "Telecommunication", "cap": "Small"},
    {"symbol": "RVNL", "name": "Rail Vikas Nigam Ltd.", "sector": "Construction", "cap": "Small"},
    {"symbol": "SJVN", "name": "SJVN Ltd.", "sector": "Energy", "cap": "Small"}
]
