"""
Central Trading Orchestrator

The brain of the quant platform. Wires the entire pipeline:
    Data Feed → State Manager → Alpha Signals → Risk Filter → Portfolio → OMS → EMS

Runs as a ticking loop on configurable intervals (default: 1-minute bars).
Supports 3 modes: BACKTEST, PAPER, LIVE.

Safety features:
- Watchdog timer kills process if main loop hangs
- Global circuit breaker on max drawdown
- Heartbeat monitoring for all components
- Graceful shutdown with position flattening
"""

import signal
import sys
import threading
import time
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any

from observability_mlops.alerting import AlertManager
from portfolio_execution.config import ExecutionMode, TradingConfig
from portfolio_execution.drop_copy_reconciler import DropCopyConfig, DropCopyReconciler
from portfolio_execution.ems import (
    ExecutionManagementSystem,
    RoutingStrategy,
)
from portfolio_execution.execution.paper_broker import PaperBrokerAdapter
from portfolio_execution.oms import (
    ManagedOrder,
    OrderManagementSystem,
    OrderSide,
    OrderStatus,
    OrderType,
)
from portfolio_execution.state_manager import Candle, MarketState, SessionStateManager
from portfolio_execution.state_persistence import RedisStateStore
from portfolio_execution.wal_journal import WALJournal
from utils.logger import get_logger

logger = get_logger("orchestrator")


@dataclass
class TradeSignal:
    """A signal generated by an alpha model, ready for risk filtering."""

    symbol: str
    direction: str  # "long" or "short"
    entry_price: float
    stop_loss: float
    target_price: float
    setup_type: str  # e.g., "ORB_LONG", "MOMENTUM_XSEC"
    confidence: float  # 0.0 to 10.0
    alpha_source: str  # Which alpha model generated this
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def reward_to_risk(self) -> float:
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.target_price - self.entry_price)
        return reward / risk if risk > 0 else 0.0


# Institutional alias and helper function for signal construction
InstitutionalSignal = TradeSignal


def build_signal(
    symbol: str,
    side: str,
    model_score: float,
    obi_features: dict[str, Any],
    market_data: dict[str, Any],
) -> InstitutionalSignal:
    ltp = market_data.get("ltp", 100.0)
    if side.upper() in ("LONG", "BUY"):
        direction = "long"
        stop_loss = ltp * 0.9925
        target_price = ltp * 1.015
    else:
        direction = "short"
        stop_loss = ltp * 1.0075
        target_price = ltp * 0.985

    return InstitutionalSignal(
        symbol=symbol,
        direction=direction,
        entry_price=ltp,
        stop_loss=stop_loss,
        target_price=target_price,
        setup_type="ALPHA_DRIVEN",
        confidence=min(abs(model_score) * 10.0, 10.0),
        alpha_source="composite",
        metadata={"obi_features": obi_features, "market_data": market_data},
    )


@dataclass
class TickData:
    """Incoming market data tick."""

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


class TradingOrchestrator:
    """
    Central orchestrator that runs the complete quant pipeline.

    Pipeline per tick:
    1. Receive market data
    2. Update session state (VWAP, EMA, ORH/ORL, market classification)
    3. Run alpha models to generate signals
    4. Filter signals through risk engine
    5. Convert approved signals to orders via OMS
    6. Route orders to broker via EMS
    7. Monitor positions and P&L
    8. Check circuit breakers
    """

    def __init__(self, config: TradingConfig | None = None):
        self.config = config or TradingConfig.from_env()

        # Validate config
        errors = self.config.validate()
        if errors:
            for err in errors:
                logger.error(f"Config error: {err}")
            if self.config.mode == ExecutionMode.LIVE:
                raise ValueError(f"Configuration errors in LIVE mode: {errors}")

        # Core components
        self.oms = OrderManagementSystem(
            max_daily_loss_pct=self.config.risk.max_daily_loss_pct,
            max_order_value_inr=self.config.risk.max_order_value_inr,
            max_order_pct_of_adv=self.config.risk.max_order_pct_of_adv,
            max_price_deviation_atr=self.config.risk.max_price_deviation_atr,
            max_trades_per_day=self.config.risk.max_trades_per_day,
            max_single_position_pct=self.config.risk.max_single_position_pct,
            max_sector_exposure_pct=self.config.risk.max_sector_exposure_pct,
        )
        self.ems = ExecutionManagementSystem(
            routing_strategy=RoutingStrategy.FAILOVER,
            order_timeout_seconds=self.config.broker.order_timeout_seconds,
            max_retries=self.config.broker.max_retry_attempts,
        )

        # Wire EMS fills back to OMS
        self.ems.set_on_fill(self.oms.on_fill)

        # New Infrastructure Components
        self.wal_journal = WALJournal()
        self.state_store = RedisStateStore()
        self.alert_manager = AlertManager()
        self.drop_copy = DropCopyReconciler(DropCopyConfig(), self.oms, self.ems)

        # Session state managers (one per instrument)
        self._state_managers: dict[str, SessionStateManager] = {}

        # Alpha models (registered by caller)
        self._alpha_models: list[Any] = []

        # Risk filters (registered by caller)
        self._risk_filters: list[Any] = []

        # Running state
        self._running = False
        self._tick_count = 0
        self._session_date: date | None = None

        # Watchdog
        self._watchdog_timer: threading.Timer | None = None
        self._last_tick_time: float = time.monotonic()

        # Peak NAV for drawdown tracking
        self._peak_nav: float = self.oms._nav
        self._current_nav: float = self.oms._nav

        # Setup graceful shutdown
        signal.signal(signal.SIGINT, self._shutdown_handler)
        signal.signal(signal.SIGTERM, self._shutdown_handler)

        logger.info(
            f"Orchestrator initialized | Mode={self.config.mode.value} | "
            f"Instruments={self.config.instruments}"
        )

    async def start(self) -> None:
        """Start async background tasks like drop copy reconciler and Redis listener."""
        logger.info("Starting background tasks...")
        await self.drop_copy.start()

        # Start redis pubsub listener for system commands (e.g. kill switch)
        try:
            import os

            import redis.asyncio as redis_async

            self._redis_client = redis_async.from_url(
                os.getenv("REDIS_URL", "redis://localhost:6379/0"), decode_responses=True
            )
            self._pubsub = self._redis_client.pubsub()
            await self._pubsub.subscribe("quant:control:system")
            import asyncio

            self._redis_task = asyncio.create_task(self._listen_to_redis())
            logger.info("Subscribed to quant:control:system")
        except Exception as e:
            logger.error(f"Failed to start Redis listener: {e}")

    async def _listen_to_redis(self):
        """Listen to Redis PubSub for system commands."""
        import json

        try:
            async for message in self._pubsub.listen():
                if message["type"] == "message":
                    try:
                        data = json.loads(message["data"])
                        if data.get("command") == "trigger_kill_switch":
                            await self.trigger_kill_switch()
                    except json.JSONDecodeError:
                        pass
        except Exception as e:
            logger.error(f"Redis listener error: {e}")

    async def stop_background_tasks(self) -> None:
        """Stop background tasks."""
        logger.info("Stopping background tasks...")
        await self.drop_copy.stop()
        if hasattr(self, "_redis_task"):
            self._redis_task.cancel()
        if hasattr(self, "_pubsub"):
            await self._pubsub.close()
        if hasattr(self, "_redis_client"):
            await self._redis_client.aclose()

    async def trigger_kill_switch(self) -> dict[str, Any]:
        """
        P1.1 Kill Switch: Halts all trading and liquidates all positions via EMS safely.
        """
        logger.critical("KILL SWITCH TRIGGERED: Liquidating and halting all activity.")
        self.oms._trading_halted = True

        event = {
            "event": "KILL_SWITCH_EXECUTED",
            "timestamp": time.time(),
        }

        from portfolio_execution.liquidation import SafeLiquidationEngine

        liquidation_engine = SafeLiquidationEngine(self.oms, self.ems)

        positions_to_close = [
            sym for sym, pos in list(self.oms._positions.items()) if pos.quantity != 0
        ]
        # Also liquidate anything that has open orders just to be safe
        symbols_with_orders = list({o.symbol for o in self.oms.open_orders})
        symbols_to_liquidate = list(set(positions_to_close + symbols_with_orders))

        liquidation_tasks = [
            liquidation_engine.trigger_emergency_liquidation(sym) for sym in symbols_to_liquidate
        ]
        import asyncio

        await asyncio.gather(*liquidation_tasks, return_exceptions=True)

        return event

    def register_alpha(self, alpha_model: Any) -> None:
        """Register an alpha model to run every tick."""
        self._alpha_models.append(alpha_model)
        logger.info(f"Registered alpha model: {alpha_model.__class__.__name__}")

    def register_risk_filter(self, risk_filter: Any) -> None:
        """Register a risk filter. Must have a filter_signal(signal, state) method."""
        self._risk_filters.append(risk_filter)
        logger.info(f"Risk filter registered: {risk_filter.__class__.__name__}")

    def initialize_session(
        self,
        previous_day_data: dict[str, dict[str, float]],
    ) -> None:
        """
        Initialize session state for all instruments.

        previous_day_data: {symbol: {high, low, close}}
        """
        for symbol in self.config.instruments:
            pd_data = previous_day_data.get(symbol, {})
            pdh = pd_data.get("high", 0.0)
            pdl = pd_data.get("low", float("inf"))
            pdc = pd_data.get("close", 0.0)

            self._state_managers[symbol] = SessionStateManager(
                symbol=symbol,
                pdh=pdh,
                pdl=pdl,
                pdc=pdc,
            )

        self._session_date = date.today()
        self.oms.reset_daily()

        # Setup broker connections
        if self.config.mode == ExecutionMode.PAPER or self.config.mode == ExecutionMode.BACKTEST:
            paper_broker = PaperBrokerAdapter(slippage_bps=5.0)
            self.ems.register_broker("paper", paper_broker, is_primary=True)

        # Note: connect_all is async but called synchronously in paper/backtest mode
        # For paper trading, connections are simulated, so we skip the async call
        if self.config.mode == ExecutionMode.LIVE:
            import asyncio

            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            try:
                loop.run_until_complete(self.ems.connect_all())
            finally:
                loop.close()
        logger.info(f"Session initialized for {self._session_date}")

    def on_tick(self, tick: TickData) -> list[ManagedOrder]:
        """
        Process a single tick of market data.

        This is the main entry point called every tick interval.
        Returns any orders that were created.
        """
        self._last_tick_time = time.monotonic()
        self._tick_count += 1
        orders_created = []

        # 1. Update session state
        state_mgr = self._state_managers.get(tick.symbol)
        if not state_mgr:
            return orders_created

        candle = Candle(
            timestamp=tick.timestamp,
            open=tick.open,
            high=tick.high,
            low=tick.low,
            close=tick.close,
            volume=tick.volume,
        )
        state_mgr.on_candle_1m(candle)

        # 2. Update market prices in OMS
        self.oms.update_market_prices({tick.symbol: tick.close})

        # 3. Check circuit breakers
        if self._check_circuit_breakers():
            return orders_created  # Trading halted

        # 4. Skip signal generation during first 15 minutes (observation period)
        if state_mgr.state == MarketState.PRE_MARKET:
            return orders_created

        # 5. Skip if market state is CHOP (no-trade condition)
        if state_mgr.state == MarketState.CHOP:
            if self._tick_count % 15 == 0:  # Log every 15 ticks
                logger.info(f"[{tick.symbol}] Market state: CHOP — skipping signals")
            return orders_created

        # 6. Generate alpha signals
        signals = self._generate_signals(tick.symbol, state_mgr)

        # 7. Filter through risk engine
        approved_signals = self._filter_signals(signals, state_mgr)

        # 8. Convert to orders and execute (TWAP logic included)
        for sig in approved_signals:
            orders = self._signal_to_orders(sig, state_mgr)
            for order in orders:
                if order and order.status == OrderStatus.VALIDATED:
                    success = self.ems.submit_order(order)
                    if success:
                        orders_created.append(order)

        # 9. Periodic status logging
        if self._tick_count % 30 == 0:  # Every 30 minutes
            self._log_status()

        return orders_created

    def _generate_signals(self, symbol: str, state_mgr: SessionStateManager) -> list[TradeSignal]:
        """Run all registered alpha models and collect signals."""
        signals = []
        for alpha in self._alpha_models:
            try:
                model_signals = alpha.generate_signals(self._state_managers)
                if model_signals:
                    # Filter signals for the current symbol only
                    symbol_signals = [s for s in model_signals if s.symbol == symbol]

                    # Store prediction in database for evaluation
                    for sig in symbol_signals:
                        try:
                            import uuid

                            from database.connection import insert_prediction

                            pred_id = str(uuid.uuid4())
                            sig.metadata["prediction_id"] = (
                                pred_id  # Store ID on signal for later linking
                            )

                            insert_prediction(
                                {
                                    "id": pred_id,
                                    "symbol": sig.symbol,
                                    "model_version": sig.alpha_source,
                                    "features_used": str(sig.metadata.get("obi_features", {})),
                                    "prediction": sig.direction.upper(),
                                    "horizon": "INTRADAY",
                                    "confidence": sig.confidence,
                                    "entry_price": sig.entry_price,
                                    "stop_loss": sig.stop_loss,
                                    "target_price": sig.target_price,
                                    "prediction_time": sig.timestamp,
                                    "expiry_time": sig.timestamp.replace(
                                        hour=15, minute=15, second=0, microsecond=0
                                    ),
                                    "regime": str(
                                        sig.metadata.get("market_data", {}).get("regime", "UNKNOWN")
                                    ),
                                    "reason": f"{sig.setup_type} by {sig.alpha_source}",
                                }
                            )
                        except Exception as db_err:
                            logger.error(f"Failed to store prediction for {sig.symbol}: {db_err}")

                    signals.extend(symbol_signals)
            except Exception as e:
                logger.error(
                    f"Alpha {alpha.__class__.__name__} error for {symbol}: {e}",
                    exc_info=True,
                )
        return signals

    def _filter_signals(
        self, signals: list[TradeSignal], state_mgr: SessionStateManager
    ) -> list[TradeSignal]:
        """Filter signals through all registered risk filters."""
        approved = []
        for sig in signals:
            passed = True
            for risk_filter in self._risk_filters:
                try:
                    if not risk_filter.filter_signal(sig, state_mgr):
                        passed = False
                        break
                except Exception as e:
                    logger.error(f"Risk filter error: {e}")
                    passed = False
                    break

            # Additional built-in filters
            if passed:
                # Minimum reward-to-risk check
                if sig.reward_to_risk < self.config.risk.min_reward_to_risk:
                    logger.debug(
                        f"[{sig.symbol}] Signal rejected: R:R {sig.reward_to_risk:.2f} "
                        f"< {self.config.risk.min_reward_to_risk}"
                    )
                    continue

                # Minimum confidence check
                if sig.confidence < 5.0:
                    logger.debug(f"[{sig.symbol}] Signal rejected: low confidence {sig.confidence}")
                    continue

                approved.append(sig)

        return approved

    def _signal_to_orders(
        self, signal: TradeSignal, state_mgr: SessionStateManager
    ) -> list[ManagedOrder]:
        """Convert an approved signal to OMS order(s). Implements LULD checks and TWAP slicing."""
        side = OrderSide.BUY if signal.direction == "long" else OrderSide.SELL

        # LULD Check: Reject if price is outside 10% daily band
        last_price = state_mgr.candles_1m[-1].close if state_mgr.candles_1m else signal.entry_price
        prev_close = (
            state_mgr.candles_1d[-1].close
            if hasattr(state_mgr, "candles_1d") and state_mgr.candles_1d
            else last_price
        )
        if prev_close > 0:
            pct_change = abs(signal.entry_price - prev_close) / prev_close
            if pct_change > 0.10:
                logger.warning(
                    f"LULD Violation: {signal.symbol} entry {signal.entry_price} exceeds 10% band from {prev_close}."
                )
                return []

        # Calculate position size based on risk budget
        risk_per_share = abs(signal.entry_price - signal.stop_loss)
        if risk_per_share <= 0:
            return []

        # Risk 0.5% of NAV per trade
        risk_budget = self.oms._nav * 0.005
        total_quantity = int(risk_budget / risk_per_share)
        if total_quantity <= 0:
            return []

        atr = state_mgr.get_atr()

        # TWAP Slicing: If order value > 10,000,000 INR, slice into 5 chunks
        order_value = total_quantity * signal.entry_price
        chunks = 5 if order_value > 10000000 else 1

        chunk_quantity = total_quantity // chunks
        orders = []

        for i in range(chunks):
            qty = chunk_quantity + (total_quantity % chunks if i == chunks - 1 else 0)
            if qty <= 0:
                continue

            order = self.oms.create_order(
                symbol=signal.symbol,
                side=side,
                quantity=qty,
                price=signal.entry_price,
                order_type=OrderType.LIMIT,
                stop_loss=signal.stop_loss,
                target_price=signal.target_price,
                setup_type=signal.setup_type,
                confidence_score=signal.confidence,
                last_price=last_price,
                atr=atr,
            )
            # Assert to prevent side inversion bugs
            assert order.side.name.upper() == (
                "BUY" if signal.direction.upper() == "LONG" else "SELL"
            ), f"Side mapping inversion detected: signal.direction={signal.direction}, order.side={order.side}"
            orders.append(order)

        return orders

    def _map_side(self, side_str: str) -> OrderSide:
        """Map side string to OrderSide enum (for compatibility)."""
        side_upper = side_str.upper()
        if side_upper in ("BUY", "LONG", "COVER"):
            return OrderSide.BUY
        elif side_upper in ("SELL", "SHORT", "EXIT_LONG"):
            return OrderSide.SELL
        else:
            raise ValueError(f"Invalid side string: {side_str}")

    def _check_circuit_breakers(self) -> bool:
        """
        Check all portfolio-level circuit breakers.
        Returns True if trading should be halted.
        """
        if self.oms.is_halted:
            return True

        # 1. Daily loss limit
        daily_loss_limit = self.oms._nav * self.config.risk.max_daily_loss_pct
        if self.oms.daily_pnl < -daily_loss_limit:
            self.oms.halt_trading(f"Daily loss limit breached: PnL=₹{self.oms.daily_pnl:,.0f}")
            return True

        # 2. Max drawdown
        unrealized_pnl = sum(p.unrealized_pnl for p in self.oms.positions.values())
        self._current_nav = self.oms._nav + self.oms.daily_pnl + unrealized_pnl
        self._peak_nav = max(self._peak_nav, self._current_nav)

        if self._peak_nav > 0:
            drawdown = (self._peak_nav - self._current_nav) / self._peak_nav
            if drawdown > self.config.risk.max_drawdown_pct:
                self.oms.halt_trading(
                    f"Max drawdown breached: {drawdown:.2%} > {self.config.risk.max_drawdown_pct:.2%}"
                )
                return True

        # 3. Gross exposure limit
        gross = self.oms.get_total_exposure()
        max_gross = self.oms._nav * self.config.risk.max_gross_exposure
        if gross > max_gross:
            logger.warning(
                f"Gross exposure ₹{gross:,.0f} exceeds limit ₹{max_gross:,.0f} — new orders blocked"
            )
            return True

        return False

    def _log_status(self) -> None:
        """Log periodic status update."""
        oms_status = self.oms.get_status_report()
        self.ems.get_status()

        states = {sym: mgr.state.value for sym, mgr in self._state_managers.items()}

        logger.info(
            f"=== STATUS | Tick #{self._tick_count} | "
            f"PnL=₹{oms_status['daily_pnl']:,.0f} | "
            f"Trades={oms_status['daily_trades']} | "
            f"Positions={len([p for p in self.oms.positions.values() if not p.is_flat])} | "
            f"Gross=₹{oms_status['gross_exposure']:,.0f} | "
            f"States={states} ==="
        )

    def _shutdown_handler(self, signum: int, frame: Any) -> None:
        """Handle graceful shutdown on SIGINT/SIGTERM."""
        logger.info(f"Shutdown signal received (sig={signum})")
        self.stop()

    def start_watchdog(self) -> None:
        """Start the watchdog timer that kills process if main loop hangs."""

        def _watchdog_check():
            elapsed = time.monotonic() - self._last_tick_time
            if elapsed > self.config.watchdog_timeout_seconds:
                logger.critical(
                    f"🚨 WATCHDOG: Main loop hung for {elapsed:.0f}s! Forcing shutdown."
                )
                self.stop()
                sys.exit(1)
            else:
                # Reschedule
                self._watchdog_timer = threading.Timer(
                    self.config.watchdog_timeout_seconds / 2, _watchdog_check
                )
                self._watchdog_timer.daemon = True
                self._watchdog_timer.start()

        self._watchdog_timer = threading.Timer(
            self.config.watchdog_timeout_seconds, _watchdog_check
        )
        self._watchdog_timer.daemon = True
        self._watchdog_timer.start()
        logger.info(f"Watchdog started (timeout={self.config.watchdog_timeout_seconds}s)")

    def stop(self) -> None:
        """Stop the orchestrator gracefully."""
        logger.info("Orchestrator stopping...")
        self._running = False

        # Cancel watchdog
        if self._watchdog_timer:
            self._watchdog_timer.cancel()

        # Cancel all open orders
        for order in self.oms.open_orders:
            self.ems.cancel_order(order)

        # Disconnect brokers (async call handled in paper/backtest mode)
        if self.config.mode == ExecutionMode.LIVE:
            import asyncio

            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            try:
                loop.run_until_complete(self.ems.disconnect_all())
            finally:
                loop.close()

        # Final status
        self._log_status()
        logger.info("Orchestrator stopped")

    def run_backtest(self, historical_ticks: list[TickData]) -> dict:
        """
        Run a backtest over historical tick data.

        Returns performance metrics.
        """
        logger.info(f"Starting backtest with {len(historical_ticks)} ticks")
        self._running = True
        all_orders = []

        for tick in historical_ticks:
            if not self._running:
                break
            orders = self.on_tick(tick)
            all_orders.extend(orders)

        self._running = False

        # Calculate performance metrics
        total_pnl = self.oms.daily_pnl
        total_trades = self.oms._daily_trade_count
        sum(1 for o in all_orders if o.status == OrderStatus.FILLED and o.average_fill_price > 0)

        result = {
            "total_pnl": total_pnl,
            "total_trades": total_trades,
            "total_orders": len(all_orders),
            "orders_filled": sum(1 for o in all_orders if o.status == OrderStatus.FILLED),
            "orders_rejected": sum(1 for o in all_orders if o.status == OrderStatus.REJECTED),
            "final_positions": {
                s: p.quantity for s, p in self.oms.positions.items() if not p.is_flat
            },
            "peak_nav": self._peak_nav,
            "final_nav": self._current_nav,
        }

        logger.info(f"Backtest complete: PnL=₹{total_pnl:,.0f} | Trades={total_trades}")
        return result
