"""initial

Revision ID: 5a3c6724ac31
Revises:
Create Date: 2026-07-04 04:55:23.179459+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5a3c6724ac31"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_ticks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("change", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_trades",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "entry_price", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "exit_price", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("entry_timestamp", sa.DateTime(), nullable=False),
        sa.Column("exit_timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("strategy_id", sa.String(length=50), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("features_used", sa.Text(), nullable=True),
        sa.Column("prediction", sa.String(length=20), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column(
            "confidence", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "entry_price", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "stop_loss", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "target_price", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("prediction_time", sa.DateTime(), nullable=False),
        sa.Column("expiry_time", sa.DateTime(), nullable=True),
        sa.Column("actual_outcome", sa.String(length=20), nullable=True),
        sa.Column("target_hit", sa.Boolean(), nullable=True),
        sa.Column("stop_hit", sa.Boolean(), nullable=True),
        sa.Column(
            "actual_return", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.Column("mfe", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("mae", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("regime", sa.String(length=50), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ltp", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("volume", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticks")
    op.drop_table("predictions")
    op.drop_table("paper_trades")
    op.drop_table("index_ticks")
    # ### end Alembic commands ###
